version: '3.6'
services:
  rstudio:
    build:
      context: .
      dockerfile: binder/Dockerfile

    ports:
      - 127.0.0.1:8888:8888
      #- 127.0.0.1:8787:8787

    volumes:
      - ./work:/home/rstudio/work

    environment:
      - DISABLE_AUTH=true

