version: '3.6'
services:
  rstudio:
    build:
      context: .
      dockerfile: docker/Dockerfile

    ports:
      - 127.0.0.1:8888:8888

    volumes:
      -  /etc/localtime:/etc/localtime:ro
      - ./work:/home/rstudio/work

    environment:
      - DISABLE_AUTH=true
