name: Release

on:
  push:
    branches: [ master ]
  tags:
    - '[0-9]+.[0-9]+.[0-9]'

# A workflows run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflows contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Build Docker Image
      #  run: make build

      - name: Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          repository: tschm/rstudio
          tag_with_ref: true
